Fix timestamp (#2023)
### What problem does this PR solve?

Fix:
- The timestamp column won't show after inserting.
- Handle ill-formed time-related types strings.

Now the python SDK will raise a exception when user inputs a ill-formed
string of time-related types.
```shell
>>> id_timestamp_table.insert({"id" : 1, "ts" : "2020-11-16+10-4-5"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/infinity-dev/lib/python3.12/site-packages/infinity/remote_thrift/table.py", line 191, in insert
    raise InfinityException(res.error_code, res.error_msg)
infinity.common.InfinityException: (7012, 'Parser error: Invalid time format (need to be HH:MM:SS). @src/parser/type/datetime/time_type.cpp:45@src/scheduler/fragment_context.cpp:1417')
```

### Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [x] Python SDK impacted, Need to update PyPI